---

- yum: name={{ item }} state=latest update_cache=yes
  with_items:
  - rsync
  - ruby
  - rubygems
  - nmap
  - libselinux-python

# should probably be handled by a security hardening role
#- name: remove nfs rpc stuff
#  yum: name={{ item }} state=absent
#  with_items:
#  - rpcbind

- name: install facter
  gem: name=facter state=latest

- name: download etcd
  shell: curl -L {{ etcd_download_url }} -o {{ etcd_download_dir }}/{{ etcd_download_filename }}

- name: verify etcd
  stat: path={{ etcd_download_dir }}/{{ etcd_download_filename }} checksum_algorithm=sha1
  register: st

- debug: msg="st == {{st}}"

- debug: msg="original checksum - '{{ etcd_download_checksum }}' "

- fail: msg="etcd checksum failed"
  when: st.stat.checksum != '{{ etcd_download_checksum }}'

- name: unarchive etcd
  unarchive: copy=no
             src={{ etcd_download_dir }}/{{ etcd_download_filename }}
             dest={{ etcd_download_dir }}
             creates="{{ etcd_download_dir }}/{{ etcd_release }}/etcd"

- name: remove etcd download
  file: path={{ etcd_download_dir }}/{{ etcd_download_filename }} state=absent

- name: copy binaries from archive into etcd dir
  shell: rsync -auv {{ etcd_download_dir }}/{{ etcd_release }}/{{ item }} {{ etcd_dir }}
  with_items:
    - etcd
    - etcdctl

- name: etcd init script
  template: src=etc/init/etcd-init.conf.j2 dest=/etc/init.d/etcd

- file: path=/etc/init.d/etcd owner=root group=root state=file mode=0755

- user: name=etcd comment="Etcd daemon" createhome=no home=/var/lib/etcd shell=/bin/sh skeleton=no

- file: path=/var/lib/etcd owner=etcd group=etcd state=directory mode=0755


- file: path=/var/log/etcd  owner=root group=etcd state=directory mode=0755
- file: path=/var/log/etcd/etcd.log owner=root group=etcd mode=0664 state=touch

- name: enable and start etcd init script
  service: name=etcd enabled=yes state=started
